export const COUNTRIES_BEGIN = 'COUNTRIES_BEGIN';
export const COUNTRIES_END = 'COUNTRIES_END';
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS';
export const COUNTRIES_SHOW_ALERT = 'COUNTRIES_SHOW_ALERT';
export const COUNTRIES_HIDE_ALERT = 'COUNTRIES_HIDE_ALERT';
export const CLEAR_COUNTRIES_STATES = 'CLEAR_COUNTRIES_STATES';