export const OVERVIEW_BEGIN = 'OVERVIEW_BEGIN';
export const OVERVIEW_END = 'OVERVIEW_END';
export const OVERVIEW_SUCCESS = 'OVERVIEW_SUCCESS';
export const OVERVIEW_FAILED = 'OVERVIEW_FAILED';
export const CLEAR_OVERVIEW_STATES = 'CLEAR_OVERVIEW_STATES';