export const OVERVIEW_BEGIN = 'OVERVIEW_BEGIN';
export const OVERVIEW_END = 'OVERVIEW_END';
export const OVERVIEW_SUCCESS = 'OVERVIEW_SUCCESS';
export const OVERVIEW_SHOW_ALERT = 'OVERVIEW_SHOW_ALERT';
export const OVERVIEW_HIDE_ALERT = 'OVERVIEW_HIDE_ALERT';
export const CLEAR_OVERVIEW_STATES = 'CLEAR_OVERVIEW_STATES';